language: java

jdk: 
  - oraclejdk7
  - openjdk7

before_script:
  - mvn help:active-profiles | sed -u -e 's/^\[.*\] //g' -e 's/^Download.*$//g' | uniq

script: mvn test | sed -u -e 's/^\[.*\] //g' -e 's/ ---$/ ---\r\n/g' -e 's/^[a-z].*$//g' -e 's/^----.*$//g' -e 's/^Download.*$//g' | uniq

# We heavily clean up Maven's spammy output with sed.
